import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useWeb3Context } from "contexts/web3Context";
import Button from '@mui/material/Button';
import { useRef } from 'react';

export default function Home() {
  //const { example } = useWeb3Context();
  const { network, web3Ref, web3Ready, address, balance, setAddress, contract, niCoinBalance } = useWeb3Context();
  const addressRef = useRef();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <strong>Web3 Ready?: </strong>
        {(!!web3Ready).toString()}
      </div>
      <div>
        <strong>Network: </strong>
        {network ?? typeof network}
      </div>

      {/* <p>
        Example Value: {example}
      </p> */}

      {network && <>
        {address && <div>
          <h3>Address</h3>
          <div><strong>{address}</strong></div>
          {balance && <div>
            <strong>Balance: </strong>
            {balance}
          </div>}
          <Button onClick={() => setAddress()} color="error">Remove</Button>
        </div>}

        {contract && <div>
          <h3>Contract</h3>
          <div><strong>{contract}</strong></div>
          {niCoinBalance && <div>
            <strong>NiCoin Balance: </strong>
            {niCoinBalance ?? typeof niCoinBalance}
          </div>}
        </div>}

        {!address && <div>
          <input ref={addressRef} placeholder="Address... e.g. 0x..." style={{width:'100%'}} />
          <Button onClick={() => setAddress(addressRef.current.value)}>Set Address</Button>
        </div>}

        <h3>Properties</h3>
        {web3Ready && <div>
          <div>
            <strong>Network: </strong>
            {network}
          </div>
          <h4>web3 properties</h4>
          <ul>
            {Object.getOwnPropertyNames(web3Ref.current).map((p,i) => <li key={i}>{p}</li>)}
          </ul>
          <h4>web3.currentProvider properties</h4>
          <ul>
            {Object.getOwnPropertyNames(web3Ref.current.currentProvider).map((p,i) => <li key={i}>{p}</li>)}
          </ul>
          <h4>web3.givenProvider properties</h4>
          <ul>
            {Object.getOwnPropertyNames(web3Ref.current.givenProvider).map((p,i) => <li key={i}>{p}</li>)}
          </ul>
          <h4>web3.eth properties</h4>
          <ul>
            {Object.getOwnPropertyNames(web3Ref.current.eth).map((p,i) => <li key={i}>{p}</li>)}
          </ul>
          <h4>web3.eth.Contract properties</h4>
          <ul>
            {Object.getOwnPropertyNames(web3Ref.current.eth.Contract).map((p,i) => <li key={i}>{p}</li>)}
          </ul>
        </div>}
      </>}

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
